version: '3.8'

services:
  pdf_to_md_app:
    build: .
    container_name: pdf_to_md_container
    ports:
      - "8501:8501"
    volumes:
      - ./models_cache:/app/models_cache
      - .:/app
    environment:
      - HF_HOME=/app/models_cache
      - TORCH_HOME=/app/models_cache
      - MARKER_HOME=/app/models_cache
    restart: unless-stopped
